apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: auto-patch
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EVXhPVEF6TVRFd04xb1hEVE13TURVeE56QXpNVEV3TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUNiCmZFTnBIWUVnOVk2emFocUZtMTZCdVl1K3JJUVFzRFRVeXpMMXVyaUVFUXcwTnRqempubGRhTWRKZEtVb3VXemcKRWhEWjN0cFJES0pLMWM0Q1NBaFdwWXFlK1FxclJSaFJxU3RxUmhic1gwVnpZc3lTbGZBM21mWlBqa2RNMTF1WApzOXhHRTJpa0J5a0I0eW5VYnE2L2N0M21xTThtNm5tSlRTSURqTUxSaHNuYzhJOHFiMEgrY3ZOOGZDaVNFTDhUCmM3bUd1OEx1T0R5WUlFVTl5V3pXZUp5MjBEdmRRU2NGM0MrRHBJRmFDZ2FodDQwTG4xZWtiWXlYYWlqWXNtRnMKSC9oSXVtcFNIOUpHYWZ6S2UyTnlqT1d4U1pxZ2lXd2FKTTRMb1VrbDFGRStDa1l5djlzSU51d2JBQmg4S0h1ZAorSlRwOGFrRTdBVVBuaWZyeDRzQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0tVTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLeERwNW5ZTy94aUJ5bEJ0T1Z1RHBPYzRKVzMKVzcyMW5DbjJwYWN4OUIvTTMwR2FUY0ZaZWJTVEJ2ck8vNUEwMWtYTTg5SlpKRUlxVWJoU2I4Vjk4Sno5eGJBZAoreXpIMEdUTm8yNU8vUk5KN1hETnphTmw1Tng3ZXR0UTFESlhMa1h0dXBMMU00M1hlb2hVM25QWDFHOU55MitFClF2R1lBbndiOXJOamZLWmszaG42MmV3Q3p3V1QyNjJqL3RWS1V1OGNRS2c0UjJHTDFlT01vL05veVVsRUZLSUMKSHBJc0IyUWl1SkZheGRvRENBZ3k3TVhEZlRJSjhiZWErdHNuWGQ0aHFyQTVqR2FDbkVvK1BWdVo4d1l2WTg4dQpPTkZzNWJHOXE2U3Z4UUJUTmRCSk5LMW1hU1JkeU9GTEQ0NHJZcDJYcnhpR0tSbFVCUHJJYy9Xamd2Yz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: autopatch-operator-system
      path: /wangjl-autopatch-pod
    #url: https://192.168.162.130:9443/wangjl-autopatch-pod
  failurePolicy: Fail
  name: auto-patch.wangjl.dev
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods

