apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: auto-patch
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCekNDQWUrZ0F3SUJBZ0lKQU01TVk0RjkwSEErTUEwR0NTcUdTSWIzRFFFQkN3VUFNQm94R0RBV0JnTlYKQkFNTUR6RTVNaTR4TmpndU1UWXlMakV6TURBZUZ3MHlNVEF6TVRnd01qSTBOVGhhRncwME9EQTRNRE13TWpJMApOVGhhTUJveEdEQVdCZ05WQkFNTUR6RTVNaTR4TmpndU1UWXlMakV6TURDQ0FTSXdEUVlKS29aSWh2Y05BUUVCCkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUw5c3k1WG1ReWw0d2diaGhiVTNpVHhFWDhvbHdWZ04rOXVJamlsUTVLZ1EKWkFPb0greWJyd1RxcmRQMklBOTBXY2VXZU9yeXBhZ1hSTFRZaFRJRm1mMGo1VmVvNHg4dyt4cmVsSmNzc05scgpHME9iaER2OEN6ZzJvTWNlQlZHRlJkeE5yVHlQWXFESXAyZDhnbUdSeUFWUWFEeXk5MEVsUU9TbFgzSXBFNWxSCjRUU3l4ZjhQSHVVWFVnZHJKbmhhMDNiMzdiRDVPeldMOEhURndjbjI3b1VDUjJuVkt4MjhtREtJZWpsUU9qemUKNXUxVk9yMjQ5cjNYSEdXalhFUlJtRHVubmZwaTliSFpYclNON3lXdE1FNmszb0F5WDdCTlBtZXpwMW5aUHdScwpDU3VrTHZWYVR2a0ZmbmhJU1YwZ213TmVXWVRoYWNyTkxwTm5JVTNJenZVQ0F3RUFBYU5RTUU0d0hRWURWUjBPCkJCWUVGQmlmRjJ3WGxOaGQ5Z0plZFNId0NmdlFUZ3hqTUI4R0ExVWRJd1FZTUJhQUZCaWZGMndYbE5oZDlnSmUKZFNId0NmdlFUZ3hqTUF3R0ExVWRFd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS1RyZUtragp3aW5xQjVBeUIrOWtiYm00ZE9oeDk5YVlyZ1I3QTZVcWdpc1VQSVRoNUprQUpWclNOcSttQ25DVkpmWWlBTXVmClc2SDMvbktGVGlXNFYxekhCR21MeGtTaGNlSzNuZEFyMGI4eGczUmtUdTZEOUh0YmNDUVVEWlVpMWdTaFFqcUgKRm1nemtUbVVDRStzVFhjc0tZd29sOGVGS1Uvbm9Vbk8yWERHd2lkRHFXL2NDVDUvMmRBWkY5cU8xWk0wd1U5NApYUkx1cVZjUEx4cGdLUno5TVRjTnNLbUV4OXZHeDlYMmJKQ1hyc0FteTVYUjgwbFhmVVdPOG5id0s2Q1hSSDJSCjJkbTJuYlZCalBqUmhxekZabUc0UmdKWVIrcEpQcUVxZ2JSQjFUMDMvSU1oalphdmxCT0VVS0xSbGZpSG0zRjIKeEZBcmViQUVGakRJZGhzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    #service:
    #  name: webhook-service
    #  namespace: system
    #  path: /wangjl-autopatch-pod
    url: https://192.168.162.130:9443/wangjl-autopatch-pod
  failurePolicy: Fail
  name: auto-patch.wangjl.dev
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods

